(defun js-indent-line ()
  (interactive)
  (beginning-of-line)
  (if (bobp)
      (indent-line-to 0)
    (let ((cur-indent -1))
      (save-excursion
	(while (= cur-indent -1)
	  (forward-line -1)
	  (if (looking-at ".+$")
	      (if (looking-at ".*[{[(]$")
		  (setq cur-indent (+ (current-indentation) tab-width))
		(setq cur-indent (current-indentation)))
	    (if (bobp) (setq cur-indent 0)))))
      (indent-line-to cur-indent))))

(defun js-tab ()
  (interactive)
  (let ((start (line-beginning-position))
	(end (point)))
    (if (or (= start end)
	    (and (<= end (line-end-position))
		 (string-match "^[ \t]*$" (buffer-substring start end))))
	(js-indent-line)
      (insert-char ?\  (- tab-width (% (current-column) tab-width))))))

(defun js-del ()
  (interactive)
  (let* ((len (+ 1 (% (- (current-column) 1) tab-width)))
	 (end (point))
	 (start (- end len)))
    (if (and (> len 0)
	     (string= (buffer-substring start end)
		      (make-string len ?\ )))
	(delete-region start end)
      (delete-backward-char 1))))

(defvar js-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "TAB") 'js-tab)
    (define-key map (kbd "DEL") 'js-del)
    map))

(add-to-list 'auto-mode-alist '("\\.js\\'" . js-mode))

(defun js-mode ()
  (interactive)
  (kill-all-local-variables)
  (use-local-map js-mode-map)
  (set (make-local-variable 'indent-tabs-mode) nil)
  (set (make-local-variable 'tab-width) 2)
  (set (make-local-variable 'comment-start) "// ")
  (set (make-local-variable 'comment-start-skip) "//+\\s-*")
  (set (make-local-variable 'require-final-newline) t)
  (setq major-mode 'js-mode)
  (setq mode-name "js"))

(provide 'js-mode)
